#Working directory:
workdir: "toy_data"

# Path to sample sheet:
samples: "samples.tsv"

# Number of threads per sample:
threads: 4 

# Merged reads quality filtering parameters:
read_filter:
    min_length: 200
    max_length: 500
    max_expected_errors: 1
    
# Clustering parameters:
cluster:
    cluster_identity: 0.97
    # Path to database for chimera filtering
    chimera_DB: "/ngs-sw/Databases/blast_RefSeq_mito/mitochondrion.16S.metazoan.faa"

# Blast parameters:
blast:
    # Path to the BLAST database, or just name if located in the taxdb folder
    blast_DB: "mitochondrion.16S.metazoan.faa" 
    # Path to the folder containing the taxdb database
    taxdb: "/ngs-sw/Databases/blast_RefSeq_mito/"
    taxmap: "db/"
    # Hard filters: Results under these will not be reported
    
    # Soft filters: Results under these will be reported but filtered out of the taxonomy analysis

    