#Working directory:
workdir: "toy_data"

# Number of threads per sample:
threads: 1 

# Path to sample sheet:
samples: "samples.tsv"

# Merged reads quality filtering parameters:
read_filter:
    min_length: 200
    max_length: 500
    max_expected_errors: 1
    
# Clustering parameters:
cluster:
    cluster_identity: 0,97
    chimera_DB: "none"

# Blast parameters:
blast:
    # Path to the BLAST database, or just name if located in the taxdb folder
    blast_DB: "mitochondrion.16S.metazoan.faa" 
    # Path to the folder containing the taxdb database
    taxdb: "/ngs-sw/Databases/blast_RefSeq_mito/"
