#Working directory (full path):

workdir: "/home/debian/NGS/FooDMe/toy_data"

# Path to sample sheet:
samples: "/home/debian/NGS/FooDMe/toy_data/samples.tsv"

# Number of threads per sample:
threads_sample: 3 
# Max number of threads to use:
threads: 6

fastp:
    length_required: 100
    qualified_quality_phred: 30
    # Options for --cut_tail:
    window_size: 4
    mean_quality: 20 

read_filter:
    min_length: 200
    max_length: 600
    max_expected_errors: 1
    
cluster:
    cluster_identity: 0.97
    # Path to database for chimera filtering
    chimera_DB: "/ngs-sw/Databases/blast_RefSeq_mito/mitochondrion.LSU.faa"

blast:
    # Path to the BLAST database
    blast_DB: "/ngs-sw/Databases/blast_RefSeq_mito/mitochondrion.LSU.faa" 
    # Path to the folder containing the taxdb database
    taxdb: "/ngs-sw/Databases/blast_RefSeq_mito/"
    # Report filters
    e_value: 1e-30
    perc_identity: 97
    qcov: 97
    # Post-filtering
    bit_score_diff: 256

taxonomy:
    names_dmp: "/home/debian/NGS/FooDMe/db/taxdump/names.dmp"
    nodes_dmp: "/home/debian/NGS/FooDMe/db/taxdump/nodes.dmp"