#Working directory:
workdir: "toy_data"

# Path to sample sheet:
samples: "samples.tsv"

# Number of threads per sample:
threads: 3 
# Max number of threads to use:
cores: 6

fastp:
    length_required: 50
    qualified_quality_phred: 15

read_filter:
    min_length: 200
    max_length: 500
    max_expected_errors: 1
    
cluster:
    cluster_identity: 0.97
    # Path to database for chimera filtering
    chimera_DB: "/ngs-sw/Databases/blast_RefSeq_mito/mitochondrion.LSU.faa"

blast:
    # Path to the BLAST database, or just name if located in the taxdb folder
    blast_DB: "mitochondrion.LSU.faa" 
    # Path to the folder containing the taxdb database
    taxdb: "/ngs-sw/Databases/blast_RefSeq_mito/"
    # Report filters
    e_value: 100
    perc_identity: 1
    qcov: 1
    # Post-filtering
    bit_score_diff: 1024

taxonomy:
    names_dmp: "/home/debian/NGS/SpezID/db/taxdump/names.dmp"
    nodes_dmp: "/home/debian/NGS/SpezID/db/taxdump/nodes.dmp"