site_name: FooDMe Documentation
site_url: https://cvua-rrw.github.io/FooDMe
site_description: Food DNA Metabarcoding analysis
site_author: Grégoire Denay, Chemisches und Veterinäruntersuchungsamt Rhein-Ruhr-Wupper - AöR
copyright: BSD 3-Clause license

repo_url: https://github.com/CVUA-RRW/FooDMe

nav:
  - Welcome: index.md
  - User Guide:
      - Overview: userguide/overview.md
      - Installation: userguide/installation.md
      - Nucleotide Database: userguide/database.md
      - Configuration: userguide/configuration.md
      - Start a run: userguide/run.md
      - View results: userguide/results.md
  - Validation & Benchmarking:
      - Benchmark mode: benchmark/benchmark.md
      - Parameter space epxloration: benchmark/paramspace.md
  - Support:
    - FAQs: faqs.md
    - Getting help: help.md
  - About: 
      - References and links: about/references_links.md
      - License: about/license.md
      - Release notes: about/changelog.md

theme:
  name: material
  logo: logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/eye
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    favicon: material/dna
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.annotate

plugins:
  - search

extra:
  version:
    provider: mike
    default: stable

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2020 - 2022 Grégoire Denay

