site_name: FooDMe Documentation
site_url: https://cvua-rrw.github.io/FooDMe
site_description: Food DNA Metabarcoding analysis
site_author: Grégoire Denay, Chemisches und Veterinäruntersuchungsamt Rhein-Ruhr-Wupper - AöR
copyright: BSD 3-Clause license

repo_url: https://github.com/CVUA-RRW/FooDMe

nav:
  - Welcome: index.md
  - User Guide:
      - Overview: userguide/overview.md
      - Installation: userguide/installation.md
      - Nucleotide Database: userguide/database.md
      - Configuration: userguide/configuration.md
      - Start a run: userguide/run.md
      - View results: userguide/results.md
  - Validation & Benchmarking:
      - Benchmark mode: benchmark/benchmark.md
      - Parameter space exploration: benchmark/paramspace.md
  - Support:
    - FAQs: faqs.md
    - Getting help: help.md
  - About: 
      - References and links: about/references_links.md
      - License: about/license.md
      - Release notes: about/changelog.md

theme:
  name: material
  logo: logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/eye
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    favicon: material/dna
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.annotate

plugins:
  - search

extra:
  version:
    provider: mike
    default: stable
  analytics:
    provider: google
    property: G-Q2XQTDWNGB
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by 
            <a href="https://github.com/CVUA-RRW/FooDMe/issues/new/?title=[Webdoc Feedback]+{title}+-+{url}" target="_blank" rel="noopener">telling us what you need</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
      You can change your cookie settings at any time.

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: >
  Copyright &copy; 2020 - 2023 Grégoire Denay -
  <a href="#__consent">Change cookie settings</a>

