# Configuration file template
# Modify the values below as deemed nescessary
# See the documentation for more informations
# ------------------------------------------------------------------------------

# Workflow control
# ----------------

# Path to the output directory, will be created if it doesn´t exist
workdir: /path/to/workdir
# Path to the sample sheet
samples: /path/to/samples.tsv
# Number of threads allocated to each job
threads_sample: 1
# Total number of threads allocated to the workflow
threads: 4

# Reference files
# ---------------

# Path to the fasta file containing primer sequences
primers_fasta: /path/to/primer/fasta
# Path to the BLAST database, including database basename but no extension
blast_DB: /path/to/BLAST_folder/db_base_name
# Path to the folder containing the `taxdb`files
taxdb: /path/to/taxdb_folder
# Path to the rankedlineage.dmp.dmp file
rankedlineage_dmp: /path/to/rankedlineage.dmp
# Path to the nodes.dmp file
nodes_dmp: /path/to/nodes.dmp

# Analysis parameters
# -------------------

# Minimal length of the reads after primer trimming
read_length_required: 50
# Minimal quality value per base
qualified_quality_phred: 20 
# Size of the sliding window for 3´ quality trimming
qctrim_window_size: 4
# Minimal quality thresold for sliding average
qctrim_mean_quality: 25 
# Should primers be trimmed on the 3' end of reads? Only relevant if sequencing through the amplicons
trim_primers_3end: True 
# Maximum error-rate allowed for primer matching
primer_error_rate: 0.1 
# Minimal length of the merge reads or ASV sequences
amplicon_min_length: 70 
# Maximal length of the merge reads or ASV sequences
amplicon_max_length: 100 
# Maximum expected errors in merged reads to keep
max_expected_errors: 2
# Maximum number of 'N' base in merged reads. If using denoising procedure this will be automatically reset to 0
max_ns: 0
# Clustering method. Choose betwen 'otu' and 'asv'
cluster_method: asv
# Minimum identity for clustering sequences in OTUs (between 0 and 1). Will be ignored if using ASVs
cluster_identity: 0.97
# Minimal size cutoff for OTUs. Will be ignored if using ASVs
cluster_minsize: 2
# Maximal number of mismatch in allowed in the read overlap. Use by ASV only.
merging_max_mismatch: 0
# Perform Chimera detection and filtering?
remove_chimera: True
# Minimal taxid frequency to reach consensus (1 to use last common ancestor)
min_consensus: 0.7
# Limit BLAST search to the taxids under the given node
taxid_filter: 0
# Use a Blocklist to prevent some taxid from appearing in the results?
# "extinct" will use the distributed list of extinct species
# Provide a path for a custom list or use None to skip filtering
blocklist: extinct
# E-value threshold for blast results
blast_evalue: 1e-10
# Minimal identity between the hit and query for blast results (in percent)
blast_identity: 97
# Minimal proportion of the query covered by a hit for blast results. A mismatch is still counting as covering (in percent)
blast_qcov: 100
# Maximum bit-score difference with the best hit for a blast result to be included in the taxonomy consensus detemination
bit_score_diff: 2

# Benchmarking parameters
# -----------------------

## DO NOT DELETE the parameters below.
## Leave the default values if not using benchmarking

# Path to the table of reference sample composition
benchmark_reference: config/reference.tsv
# Minimal component ratio to be considered atrue result
benchmark_threshold: 0.1
# Maximal rank of component to be considered a true result
benchmark_rank: genus
