name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Run workflow
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "-j 1 --use-conda --conda-cleanup-pkgs cache --conda-prefix envs --show-failed-logs" 
        stagein: "pip install pandas taxidtools"
    
    - name: Report
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "--report snkmk_report.html" 
    
    - name: Archive report for checks
      uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: foodme-reports
        path: |
          .tests/reports/report.html
          .tests/snkmk_report.html
        retention-days: 7
    
    - name: Archive all results on fail
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: foodme-fail
        path: |
          .tests/reports
          .tests/NTC
          .tests/logs
          .tests/Lasagne_horse
          .tests/Lasagen_clean
          .tests/PIPELINE_STATUS
        retention-days: 7
