name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Testing_ASV:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "-j 1 --use-conda --conda-cleanup-pkgs cache --conda-prefix envs --show-failed-logs" 
        stagein: |
            conda config --set channel_priority strict
    
    - name: Archive logs on fail
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: foodme-fail-asv
        path: .tests/logs/
        if-no-files-found: error
        retention-days: 3
  
  Testing_OTU:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "-j 1 --use-conda --conda-cleanup-pkgs cache --conda-prefix envs --show-failed-logs --configfile .tests/config/config_otu.yaml"
        stagein: |
            conda config --set channel_priority strict
    
    - name: Archive logs on fail
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: foodme-fail-otu
        path: .tests/logs/
        if-no-files-found: error
        retention-days: 3
  
  Testing_benchmark:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "benchmark -j 1 --use-conda --conda-cleanup-pkgs cache --conda-prefix envs --show-failed-logs --configfile .tests/config/config_benchmark.yaml"
        stagein: |
          conda config --set channel_priority strict
    
    - name: Archive logs on fail
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: foodme-fail-bchmrk
        path: .tests/logs/
        if-no-files-found: error
        retention-days: 3
  