name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Test workflow (ASV)
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "-j 1 --use-conda --conda-cleanup-pkgs cache --conda-prefix envs --show-failed-logs" 
    
    - name: Report (ASV)
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "--report snkmk_report.html" 
    
    - name: Test workflow (OTU)
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "-j 1 --use-conda --conda-cleanup-pkgs cache --conda-prefix envs --show-failed-logs --configfile .tests/config/config_otu.yaml"
        stagein: |
          find .tests/ -maxdepth 1 -mindepth 1 ! -name "config" ! -name "data" | xargs rm -r
    
    - name: Report (OTU)
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: '.tests'
        snakefile: 'workflow/Snakefile'
        args: "--report snkmk_report_otu.html" 
    
    - name: Archive report for checks
      uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: foodme-reports
        path: |
          .tests/snkmk_report.html
          .tests/snkmk_report_otu.html
        retention-days: 7
    
    - name: Archive logs on fail
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: foodme-fail
        path: .tests/logs/
        if-no-files-found: error
        retention-days: 7
