name: Lint Code Base

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Lint
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true

# jobs:
  # formatting:
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v2
    # - name: Checkout code
      # uses: textbook/git-checkout-submodule-action@2.0.0
    # - name: Formatting
      # uses: github/super-linter@v4
      # env:
        # VALIDATE_ALL_CODEBASE: false
        # DEFAULT_BRANCH: master
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # VALIDATE_SNAKEMAKE_SNAKEFMT: true
  
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: '.tests'
        snakefile: workflow/Snakefile
        args: "--lint"