name: Lint Code Base

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Lint
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
        VALIDATE_PYTHON_FLAKE8: true
        VALIDATE_R: true
        VALIDATE_MARKDOWN: true

  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Linting
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: '.tests'
        snakefile: workflow/Snakefile
        args: "--lint"