name: Lint Code Base

on:
# Will fail linting because of: 
# - conda env warning
# - log warning
# snakefmt will fail until update to 0.4.4
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Lint
      uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true
        VALIDATE_SNAKEMAKE_LINT: true
