name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Checkout submodule
      run: git submodule update --init scripts/taxidTools
      # uses: textbook/git-checkout-submodule-action@master
    
    - name: Conda setup
      uses: s-weigand/setup-conda@v1.0.5
      with: 
        activate-conda: true
        update-conda: false
        conda-channels: 'defaults,r,bioconda'
    
    - name: Setup main env
      run: conda install snakemake pandas
    
    - name: Create workflow envs
      run: snakemake --cores 1 --use-conda --conda-prefix /usr/share/miniconda --conda-create-envs-only --conda-cleanup-pkgs cache
    
    - name: Run workflow
      run: snakemake --cores 1 --use-conda --conda-prefix /usr/share/miniconda --show-failed-logs
      # uses: snakemake/snakemake-github-action@v1.14.0
      # with:
        # directory: 'tests'
        # snakefile: 'Snakefile'
        # args: "-j 10 --use-conda --conda-cleanup-pkgs cache --show-failed-logs"
        # stagein: |
          # export TMPDIR=/tmp
