name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # - name: Checkout submodule
      # run: git submodule update --init scripts/taxidTools
    
    # - name: Create workflow envs # Only creates envs
      # uses: snakemake/snakemake-github-action@v1
      # with:
        # directory: 'tests'
        # snakefile: 'Snakefile'
        # args: "-j 1 --use-conda --conda-cleanup-pkgs cache --conda-prefix envs --conda-create-envs-only"
        # stagein: "conda install pandas taxidtools"
    
    - name: Run workflow
      uses: snakemake/snakemake-github-action@v1.23.0
      with:
        directory: 'tests'
        snakefile: 'Snakefile'
        args: "-j 1 --use-conda --conda-cleanup-pkgs cache --conda-prefix envs --show-failed-logs" 
        # stagein: "conda install pandas'>=1.3' taxidtools'>=2.2.3'"
        stagein: "pip install pandas'>=1.3' taxidtools'>=2.2.3'"
    
    - name: Archive results
      uses: actions/upload-artifact@v2
      with:
        name: foodme-run
        path: |
          tests/reports
          tests/NTC
          tests/logs
          tests/Lasagne_horse
          tests/Lasagen_clean
          tests/PIPELINE_STATUS
        retention-days: 5
    