name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.14.0
      with:
        directory: 'tests'
        snakefile: 'Snakefile'
        args: "-j 10 --use-conda --conda-cleanup-pkgs cache --show-failed-logs"
        stagein: |
          export TMPDIR=/tmp